theme: jekyll-theme-minimal
title: This is Xashzaya's page on github, idk what else to say about this tbh.
description: Bookmark this to keep an eye on my project updates! #huh, the website now uses the index.html i created. Okay.
